# Generated by Django 5.2.11 on 2026-03-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_blog_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
