# Generated by Django 6.0 on 2025-12-31 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productimage_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cover_image',
            new_name='image',
        ),
    ]
