# Generated by Django 6.0 on 2026-01-06 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',)},
        ),
    ]
