# Generated by Django 6.0 on 2026-01-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_productinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinformation',
            name='weight',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
