# Generated by Django 6.0 on 2026-01-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_height_product_length_product_madein_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='categoryimage',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
