# Generated by Django 6.0 on 2026-01-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_productcategory_categoryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isnew',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
