# Generated by Django 6.0 on 2026-01-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_product_isnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isnew',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
