# Generated by Django 6.0 on 2026-01-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_product_isnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aviability',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
