# Generated by Django 6.0 on 2026-01-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_product_aviability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='aviability',
            new_name='avaibility',
        ),
    ]
