# Generated by Django 6.0 on 2026-01-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_rename_aviability_product_avaibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='avaibility',
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
