# Generated by Django 5.2.11 on 2026-02-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_productcategory_title_az_productcategory_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='title_az',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
