# Generated by Django 5.2.11 on 2026-02-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_alter_producttag_title_alter_producttag_title_az_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='product.producttag'),
        ),
    ]
