# Generated by Django 5.2.11 on 2026-02-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_product_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='products', to='product.producttag'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='title_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
