# Generated by Django 5.2.11 on 2026-02-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_alter_productcategory_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='producttag',
            name='title_az',
        ),
    ]
