# Generated by Django 5.2.11 on 2026-02-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_remove_productcategory_title_az_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='producttag',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='producttag',
            name='title_ru',
        ),
    ]
