# Generated by Django 5.2.11 on 2026-02-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_remove_productcategory_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producttag',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producttag',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
