# Generated by Django 5.2.11 on 2026-02-28 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_productcategory_title_en_productcategory_title_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.productcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='categoryimage',
            field=models.ImageField(default=3, upload_to='category_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(default=11, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='title',
            field=models.CharField(default=13, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producttag',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
