# Generated by Django 6.0 on 2026-01-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_profil_image_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profil_image',
            new_name='profile_image',
        ),
    ]
